# Generated by Django 5.2.4 on 2025-07-14 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "Task_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Title", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=255)),
                ("Status", models.CharField(max_length=50)),
                ("Created_At", models.DateTimeField()),
                ("Due_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "User_Answer_Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Answer_Text", models.TextField()),
                ("Is_Correct", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="UserQuiz",
            fields=[
                (
                    "User_Quiz_Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Total_Questions", models.IntegerField()),
                ("Total_Correct", models.IntegerField()),
                ("Started_At", models.DateTimeField()),
                ("Completed_At", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserSubjectScore",
            fields=[
                (
                    "User_Subject_Score_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "Aggregate_Score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("Last_Updated", models.DateTimeField()),
            ],
        ),
    ]
