# Generated by Django 5.2.4 on 2025-07-18 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participation", "0001_initial"),
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="user_quiz_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="participation.quiz"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.subject"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user_quiz_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="participation.quiz",
            ),
        ),
    ]
