# Generated by Django 5.2.4 on 2025-07-14 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participation", "0001_initial"),
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="User_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="Question_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizzes.question"
            ),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="Quiz_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizzes.quiz"
            ),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="User_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="User_Quiz_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="participation.userquiz"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="User_Quiz_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="participation.userquiz"
            ),
        ),
        migrations.AddField(
            model_name="usersubjectscore",
            name="Subject_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizzes.subject"
            ),
        ),
        migrations.AddField(
            model_name="usersubjectscore",
            name="User_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
