# Generated by Django 5.2.4 on 2025-07-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="Answer_Text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="Is_Correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userquiz",
            name="Completed_At",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquiz",
            name="Score",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
