# Generated by Django 5.2.4 on 2025-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="total_correct",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="total_questions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
