# Generated by Django 5.2.4 on 2025-07-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0003_alter_useranswer_answer_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Type",
            field=models.CharField(
                choices=[("quiz", "Quiz"), ("reminder", "Reminder"), ("todo", "To-Do")],
                default="todo",
                max_length=20,
            ),
        ),
    ]
