# Generated by Django 5.2.4 on 2025-08-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0003_alter_quiz_total_correct_alter_quiz_total_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
