# Generated by Django 5.2.4 on 2025-07-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0004_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="User_Quiz_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="participation.userquiz",
            ),
        ),
    ]
