# Generated by Django 5.2.4 on 2025-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0005_alter_task_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="total_correct",
            field=models.IntegerField(default=0),
        ),
    ]
