# Generated by Django 5.2.4 on 2025-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0006_alter_quiz_total_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
    ]
