# Generated by Django 5.2.4 on 2025-07-11 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "Quiz_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "Subject_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "User_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Role", models.CharField(max_length=50)),
                ("Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=255, unique=True)),
                ("Password_Hash", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "Question_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Question_Text", models.TextField()),
                ("Correct_Answer", models.TextField()),
                (
                    "Quiz_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="Subject_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.subject"
            ),
        ),
        migrations.CreateModel(
            name="UserQuiz",
            fields=[
                (
                    "User_Quiz_Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Total_Questions", models.IntegerField()),
                ("Total_Correct", models.IntegerField()),
                ("Started_At", models.DateTimeField()),
                ("Completed_At", models.DateTimeField()),
                (
                    "Quiz_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "User_Answer_Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Answer_Text", models.TextField()),
                ("Is_Correct", models.BooleanField()),
                (
                    "Question_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "User_Quiz_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.userquiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "Task_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Title", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=255)),
                ("Status", models.CharField(max_length=50)),
                ("Created_At", models.DateTimeField()),
                ("Due_date", models.DateTimeField()),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "User_Quiz_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.userquiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubjectScore",
            fields=[
                (
                    "User_Subject_Score_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "Aggregate_Score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("Last_Updated", models.DateTimeField()),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.subject"
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
