# Generated by Django 5.2.4 on 2025-07-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Role",
            new_name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Password_Hash",
        ),
    ]
