# Generated by Django 5.2.4 on 2025-07-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_rename_email_user_email_rename_name_user_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="Question_ID",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="Subject_ID",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="Quiz_ID",
        ),
        migrations.RemoveField(
            model_name="usersubjectscore",
            name="Subject_ID",
        ),
        migrations.RemoveField(
            model_name="task",
            name="User_ID",
        ),
        migrations.RemoveField(
            model_name="task",
            name="User_Quiz_ID",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="User_Quiz_ID",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="User_ID",
        ),
        migrations.RemoveField(
            model_name="usersubjectscore",
            name="User_ID",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
        migrations.DeleteModel(
            name="UserQuiz",
        ),
        migrations.DeleteModel(
            name="UserSubjectScore",
        ),
    ]
