# Generated by Django 5.2.4 on 2025-07-21 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_assigned_teacher_subject_teachers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "teacher"},
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
