# Generated by Django 5.2.4 on 2025-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin / HR"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
